language: rust
script:
  - mkdir -p webpwrapper/build && cd webpwrapper/build
  - cmake ..
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then make && make install; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then cmake --build . --config Release && cmake --install . ; fi
  - cd ../..
  - cargo build --verbose --release --all
  - cargo test --release

cache:
  cargo: true

rust:
  - stable
  - beta
  - nightly

env:
  global:
    - RUST_BACKTRACE=1
    - BADGE=osx
    - BADGE=linux
    - BADGE=windows

arch:
  - amd64
  - arm64
  - ppc64le

os:
  - windows
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
    - os: windows
  exclude:
    - os: osx
      env: 
        - BADGE=linux
        - BADGE=windows
    - os: linux
      env: 
        - BADGE=osx
        - BADGE=windows
    - os: windows
      env:
        - BADGE=osx
        - BADGE=linux

before_script:
  - curl https://codeload.github.com/webmproject/libwebp/tar.gz/v1.1.0 -o libwebp-1.1.0.tar.gz
  - tar -xzf libwebp-1.1.0.tar.gz
  - mkdir -p libwebp-1.1.0/build && cd libwebp-1.1.0/build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../deps -DWEBP_BUILD_CWEBP=OFF -DWEBP_BUILD_DWEBP=OFF -DWEBP_BUILD_GIF2WEBP=OFF -DWEBP_BUILD_IMG2WEBP=OFF -DWEBP_BUILD_VWEBP=OFF -DWEBP_BUILD_WEBPINFO=OFF -DWEBP_BUILD_WEBPMUX=OFF -DWEBP_BUILD_EXTRAS=OFF -DWEBP_BUILD_WEBP_JS=OFF -DWEBP_BUILD_ANIM_UTILS=OFF -DWEBP_NEAR_LOSSLESS=ON ..
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then make && make install; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then cmake --build . --config Release && cmake --install . ; fi
  - cd ../..

