language: rust
script:
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then make libwebpwrapper.a; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then setx PATH="%PATH%;C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64" ; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then cl.exe -c webpwrapper.c -I./deps/include; lib.exe webpwrapper.obj /out:lib/webpwrapper.lib; fi 
  - cargo build --verbose --release --all
  - cargo test --release

cache:
  cargo: true

rust:
  - stable
  - beta
  - nightly

env:
  global:
    - RUST_BACKTRACE=1

arch:
  - amd64
  - arm64
  - ppc64le

os:
  - windows
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

before_script:
  - rm v1.1.0.tar.gz || true
  - rm -rf libwebp-1.1.0 || true
  - curl https://codeload.github.com/webmproject/libwebp/tar.gz/v1.1.0 -o v1.1.0.tar.gz
  - tar -xzf v1.1.0.tar.gz
  - mkdir -p libwebp-1.1.0/build && cd libwebp-1.1.0/build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../deps -DWEBP_BUILD_CWEBP=OFF -DWEBP_BUILD_DWEBP=OFF -DWEBP_BUILD_GIF2WEBP=OFF -DWEBP_BUILD_IMG2WEBP=OFF -DWEBP_BUILD_VWEBP=OFF -DWEBP_BUILD_WEBPINFO=OFF -DWEBP_BUILD_WEBPMUX=OFF -DWEBP_BUILD_EXTRAS=OFF -DWEBP_BUILD_WEBP_JS=OFF -DWEBP_BUILD_ANIM_UTILS=OFF -DWEBP_NEAR_LOSSLESS=ON ..
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then cmake --build . --config Release ; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then cmake --install . ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then make && make install; fi
  - cd ../..

