language: rust
script:
  - make libwebpwrapper.a
  - cargo build --verbose --release --all
  - cargo test --release

cache:
  cargo: true

rust:
  - stable
  - beta
  - nightly

env:
  global:
    - RUST_BACKTRACE=1

arch:
  - amd64
  - arm64
  - ppc64le

os:
  - windows
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
    - os: windows

before_script:
  - rm v1.1.0.tar.gz || true
  - rm -rf libwebp-1.1.0 || true
  - make libwebp
  - rm -rf libwebp-1.1.0

