language: rust
script:
  - make
  - cargo build --verbose --all
  - cargo test
  - echo "All done, have fun!"

cache:
  cargo: true

rust:
  - stable
  - beta
  - nightly

env:
  global:
    - RUST_BACKTRACE=1

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

before_script:
  - curl https://codeload.github.com/webmproject/libwebp/tar.gz/v1.1.0 -o v1.1.0.tar.gz && tar -xzf v1.1.0.tar.gz
  - mkdir -p libwebp-1.1.0/build && pushd libwebp-1.1.0/build
  - cmake -D CMAKE_BUILD_TYPE=Release .. && sudo make install && popd
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install git-lfs; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh -o ./script.deb.sh; sudo chmod +x ./script.deb.sh; sudo ./script.deb.sh; sudo apt-get install -y git-lfs; fi
  - git lfs install

