language: rust
script:
  - make libwebpwrapper.a
  - cargo build --verbose --all
  - cargo test

cache:
  cargo: true

rust:
  - stable
  - beta
  - nightly

env:
  global:
    - RUST_BACKTRACE=1

arch:
  - amd64
  - arm64
  - ppc64le

os:
  - windows
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
    - os: windows

before_script:
  - rm v1.1.0.tar.gz || true
  - rm -rf libwebp-1.1.0 || true
  - curl https://codeload.github.com/webmproject/libwebp/tar.gz/v1.1.0 -o v1.1.0.tar.gz && tar -xzf v1.1.0.tar.gz
  - mkdir -p libwebp-1.1.0/build && pushd libwebp-1.1.0/build
  - cmake -D CMAKE_BUILD_TYPE=Release .. && sudo make install && popd

